### ISSUE TITLE
Handle Worker Resources

### ISSUE THREAD

**Issue by PythonFZ** [zincware/dask4dvc#2]
Currently there is no way of setting the resources required per Node. There are ways to define this for the `client.submit` via https://distributed.dask.org/en/stable/resources.html.

My Idea would be, to add a `dask4dvc.yaml` file (or alternatively the `meta` key in `dvc.yaml` https://distributed.dask.org/en/stable/resources.html) to define the resources that should be acquired for the respective Node.

```yaml
node1:
  GPU: 1
  MEMORY: 100e9

node2:
  MEMORY: 16e9

node3:
  GPU: 3
  MEMORY: 128e9
```

we parse this file, if it exists and use it here:
https://github.com/zincware/dask4dvc/blob/86396b2682b5b42d3bf2e12c7287f5bc3a25bd1f/dask4dvc/utils/graph.py#L96-L101

Furthermore, we might also want to have a general section e.g. for https://jobqueue.dask.org/en/latest/generated/dask_jobqueue.SLURMCluster.html

```yaml
cluster:
   slurm:
      project: "my-project"
```
